title: Clément Roblot - Blog
description: Blog
author: Clément Roblot
logo: /static/img/logoColor.png
about: Freelance C++/Qt developper

baseurl: ""
url: "index.html"

allowsearch: false
allowgoogleanalytics: true

disqus_shortname: karlito139
google_analytics: UA-108001537-1

enableTags: true
tagarray: []

paginate: 5
per_page: 5
paginate_path: "/blog/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
