title: Florian Roussel - Blog
description: Blog
author: Florian Roussel
logo: /static/img/red-panda.svg
about: C++/Qt Software Engineer

baseurl: ""
url: "127.0.0.1"

allowsearch: false
allowgoogleanalytics: true

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
plugins: [jekyll-paginate, jekyll-gist]
